# generated by datamodel-codegen:
#   filename:  authapi.json
#   timestamp: 2026-01-16T16:32:50+00:00

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel


class AuthUser(BaseModel):
    id: str | None = None
    name: str
    email: str
    emailVerified: bool | None = False
    image: str | None = None
    createdAt: AwareDatetime
    updatedAt: AwareDatetime
    role: str | None = None
    banned: bool | None = False
    banReason: str | None = None
    banExpires: AwareDatetime | None = None
    username: str | None = None
    displayUsername: str | None = None
    stripeCustomerId: str | None = None


class AuthSession(BaseModel):
    id: str | None = None
    expiresAt: AwareDatetime
    token: str
    createdAt: AwareDatetime
    updatedAt: AwareDatetime
    ipAddress: str | None = None
    userAgent: str | None = None
    userId: str
    impersonatedBy: str | None = None


class AuthAccount(BaseModel):
    id: str | None = None
    accountId: str
    providerId: str
    userId: str
    accessToken: str | None = None
    refreshToken: str | None = None
    idToken: str | None = None
    accessTokenExpiresAt: AwareDatetime | None = None
    refreshTokenExpiresAt: AwareDatetime | None = None
    scope: str | None = None
    password: str | None = None
    createdAt: AwareDatetime
    updatedAt: AwareDatetime


class AuthVerification(BaseModel):
    id: str | None = None
    identifier: str
    value: str
    expiresAt: AwareDatetime
    createdAt: AwareDatetime
    updatedAt: AwareDatetime


class AuthApikey(BaseModel):
    id: str | None = None
    name: str | None = None
    start: str | None = None
    prefix: str | None = None
    key: str | None = None
    userId: str | None = None
    refillInterval: float | None = None
    refillAmount: float | None = None
    lastRefillAt: AwareDatetime | None = None
    enabled: bool | None = True
    rateLimitEnabled: bool | None = True
    rateLimitTimeWindow: float | None = 86400000
    rateLimitMax: float | None = 10
    requestCount: float | None = 0
    remaining: float | None = None
    lastRequest: AwareDatetime | None = None
    expiresAt: AwareDatetime | None = None
    createdAt: AwareDatetime | None = None
    updatedAt: AwareDatetime | None = None
    permissions: str | None = None
    metadata: str | None = None


class AuthSubscription(BaseModel):
    id: str | None = None
    plan: str
    referenceId: str
    stripeCustomerId: str | None = None
    stripeSubscriptionId: str | None = None
    status: str | None = 'incomplete'
    periodStart: AwareDatetime | None = None
    periodEnd: AwareDatetime | None = None
    trialStart: AwareDatetime | None = None
    trialEnd: AwareDatetime | None = None
    cancelAtPeriodEnd: bool | None = False
    seats: float | None = None
