# generated by datamodel-codegen:
#   filename:  authapi.json
#   timestamp: 2026-01-14T08:44:40+00:00

from __future__ import annotations

from pydantic import AwareDatetime, BaseModel


class AuthUser(BaseModel):
    id: str | None = None
    name: str
    email: str
    emailVerified: bool | None = False
    image: str | None = None
    createdAt: AwareDatetime
    updatedAt: AwareDatetime
    role: str | None = None
    banned: bool | None = False
    banReason: str | None = None
    banExpires: AwareDatetime | None = None
    username: str | None = None
    displayUsername: str | None = None


class AuthSession(BaseModel):
    id: str | None = None
    expiresAt: AwareDatetime
    token: str
    createdAt: AwareDatetime
    updatedAt: AwareDatetime
    ipAddress: str | None = None
    userAgent: str | None = None
    userId: str
    impersonatedBy: str | None = None


class AuthAccount(BaseModel):
    id: str | None = None
    accountId: str
    providerId: str
    userId: str
    accessToken: str | None = None
    refreshToken: str | None = None
    idToken: str | None = None
    accessTokenExpiresAt: AwareDatetime | None = None
    refreshTokenExpiresAt: AwareDatetime | None = None
    scope: str | None = None
    password: str | None = None
    createdAt: AwareDatetime
    updatedAt: AwareDatetime


class AuthVerification(BaseModel):
    id: str | None = None
    identifier: str
    value: str
    expiresAt: AwareDatetime
    createdAt: AwareDatetime
    updatedAt: AwareDatetime
