"""rename session token column

Revision ID: 0fbffc0968f9
Revises: b6d73d3d988a
Create Date: 2026-01-16 22:08:27.978754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0fbffc0968f9'
down_revision: Union[str, Sequence[str], None] = 'b6d73d3d988a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_state', sa.Column('session_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_index(op.f('ix_session_state_better_auth_session_token'), table_name='session_state')
    op.create_index(op.f('ix_session_state_session_token'), 'session_state', ['session_token'], unique=False)
    op.drop_column('session_state', 'better_auth_session_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_state', sa.Column('better_auth_session_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_session_state_session_token'), table_name='session_state')
    op.create_index(op.f('ix_session_state_better_auth_session_token'), 'session_state', ['better_auth_session_token'], unique=False)
    op.drop_column('session_state', 'session_token')
    # ### end Alembic commands ###
