"""document metrics

Revision ID: b6d73d3d988a
Revises: 32708e2a91b3
Create Date: 2026-01-16 21:04:03.017551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b6d73d3d988a'
down_revision: Union[str, Sequence[str], None] = '32708e2a91b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_state', sa.Column('document_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('session_state', sa.Column('generated_document_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_state', 'generated_document_metrics')
    op.drop_column('session_state', 'document_metrics')
    # ### end Alembic commands ###
