"""field name change

Revision ID: fbd8c9048405
Revises: 1ab532dbc5de
Create Date: 2026-01-14 04:52:01.960818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fbd8c9048405'
down_revision: Union[str, Sequence[str], None] = '1ab532dbc5de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('auth_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_index(op.f('ix_user_better_auth_user_id'), table_name='user')
    op.create_index(op.f('ix_user_auth_user_id'), 'user', ['auth_user_id'], unique=True)
    op.drop_column('user', 'better_auth_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('better_auth_user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_user_auth_user_id'), table_name='user')
    op.create_index(op.f('ix_user_better_auth_user_id'), 'user', ['better_auth_user_id'], unique=True)
    op.drop_column('user', 'auth_user_id')
    # ### end Alembic commands ###
